"""Tests for practice drill generation and availability.

Every drill is derived deterministically from content_json, so none of these
need Ollama. Piper is stubbed for the listening drill.
"""

import json
import random
import re
from unittest.mock import patch

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.database import Base, get_db
from app.main import app
from app.models import Course, Lesson, Module
from app.services.drills import (
    build_listen,
    build_mcq,
    build_order,
    build_pronounce,
    collect_concepts,
    collect_step_sets,
    drill_availability,
    load_course_lessons,
)
from tests.conftest import TEST_USER_ID

TTS_PATCH = "app.routes.drills.synthesize_speech"


def _content(n_concepts: int, steps: int = 4) -> str:
    """A lesson body, written the way the enrichment prompt actually produces one.

    Note what the definition does NOT do: name its own concept. An earlier
    version of this fixture defined `Concept {i}` as "…definition for concept
    {i}…", which is precisely the property that broke the choice drills — the
    prompt text contained the answer. The fixture encoded the bug, so no test
    could have caught it; that is Defect 8 in the report, twice over now.
    """
    return json.dumps(
        {
            "key_concepts": [
                {
                    "name": f"Concept {i}",
                    "definition": (
                        f"The mechanism that governs case {i}, the conditions "
                        "under which it applies and why it behaves that way."
                    ),
                    "example": f"example_{i}()" if i % 2 == 0 else "",
                }
                for i in range(n_concepts)
            ],
            # Bodies must differ once the ordinal marker is stripped, or the steps
            # become indistinguishable and the ordering drill is unsolvable.
            "worked_example": "\n".join(
                f"Step {i}: do thing number {i}." for i in range(steps)
            ),
            "common_pitfalls": [],
            "practice_prompts": [],
        }
    )


def _clues(n_concepts: int) -> str:
    """Clues for a lesson body from `_content`, in the shape `Lesson.clues` reads."""
    return json.dumps({
        "clues": {
            f"Concept {i}": (
                f"A description of the situation in case {i} and what follows from "
                "it, phrased so the listener has to recognise it rather than hear it."
            )
            for i in range(n_concepts)
        }
    })


def _lesson_clues(clues, index: int, content: str | None) -> str | None:
    """The stored clue set for one seeded lesson.

    Generated by a separate pass from enrichment, so it is absent whenever the
    content is. `clues` overrides that per lesson, which is how the tests model a
    lesson that has been enriched but has not had its clues written yet.
    """
    if clues is not None:
        return clues[index]
    if not content:
        return None
    return _clues(len(json.loads(content)["key_concepts"]))


@pytest.fixture()
def test_engine():
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(engine)
    yield engine
    Base.metadata.drop_all(engine)


@pytest.fixture()
def db_session(test_engine):
    db = sessionmaker(bind=test_engine, autocommit=False, autoflush=False)()
    try:
        yield db
    finally:
        db.close()


@pytest.fixture(autouse=True)
def isolated_audio_dir(tmp_path, monkeypatch):
    """Drill audio is cached on disk; without this, a WAV written by one test
    satisfies the cache in the next and masks a synthesis failure."""
    monkeypatch.setattr("app.routes.drills._AUDIO_DIR", tmp_path)
    yield


@pytest.fixture()
def client(test_engine):
    TestingSession = sessionmaker(bind=test_engine, autocommit=False, autoflush=False)

    def override_get_db():
        db = TestingSession()
        try:
            yield db
        finally:
            db.close()

    app.dependency_overrides[get_db] = override_get_db
    with TestClient(app) as c:
        yield c
    app.dependency_overrides.clear()


def _seed(
    db_session,
    *,
    lesson_contents,
    clues=None,
    category="Programming",
    goal="Learn things",
    title="A Course",
):
    course = Course(
        user_id=TEST_USER_ID,
        goal=goal, duration="short_term", category=category, title=title, description="d"
    )
    db_session.add(course)
    db_session.flush()
    module = Module(course_id=course.id, order_index=0, title="M", description="d")
    db_session.add(module)
    db_session.flush()
    for i, content in enumerate(lesson_contents):
        db_session.add(
            Lesson(
                module_id=module.id,
                order_index=i,
                title=f"Lesson {i}",
                description="Prose summary.",
                duration_minutes=20,
                content_json=content,
                clues_json=_lesson_clues(clues, i, content),
            )
        )
    db_session.commit()
    db_session.refresh(course)
    return course


# ---------------------------------------------------------------------------
# Availability
# ---------------------------------------------------------------------------

def test_unenriched_course_offers_nothing_but_explains_why(client, db_session):
    course = _seed(db_session, lesson_contents=[None, None, None])
    body = client.get(f"/courses/{course.id}/drills").json()

    assert body["enriched_lessons"] == 0
    assert body["total_lessons"] == 3
    assert all(d["available"] is False for d in body["drills"])
    assert all(d["reason"] for d in body["drills"])
    mcq = next(d for d in body["drills"] if d["kind"] == "mcq")
    assert "Open a lesson" in mcq["reason"]


def test_enriched_course_offers_content_drills(client, db_session):
    course = _seed(db_session, lesson_contents=[_content(4), None])
    drills = {d["kind"]: d for d in client.get(f"/courses/{course.id}/drills").json()["drills"]}

    assert drills["mcq"]["available"] is True
    assert drills["match"]["available"] is True
    assert drills["order"]["available"] is True
    assert drills["listen"]["available"] is True


def test_pronounce_is_language_courses_only(client, db_session):
    course = _seed(db_session, lesson_contents=[_content(4)], category="Programming")
    drills = {d["kind"]: d for d in client.get(f"/courses/{course.id}/drills").json()["drills"]}
    assert drills["pronounce"]["available"] is False
    assert "language courses" in drills["pronounce"]["reason"]


def test_pronounce_available_for_a_language_course(client, db_session):
    course = _seed(
        db_session,
        lesson_contents=[_content(4)],
        category="Language",
        goal="Learn conversational Spanish",
        title="Spanish for Beginners",
    )
    body = client.get(f"/courses/{course.id}/drills").json()
    drills = {d["kind"]: d for d in body["drills"]}
    assert body["target_language"] == "es"
    assert drills["pronounce"]["available"] is True


def test_too_few_concepts_leaves_drills_unavailable(client, db_session):
    course = _seed(db_session, lesson_contents=[_content(2, steps=2)])
    drills = {d["kind"]: d for d in client.get(f"/courses/{course.id}/drills").json()["drills"]}
    assert drills["mcq"]["available"] is False       # needs 3
    assert drills["match"]["available"] is False     # needs 4
    assert drills["order"]["available"] is False     # needs 3 steps


def test_availability_404s_for_unknown_course(client):
    assert client.get("/courses/nope/drills").status_code == 404


# ---------------------------------------------------------------------------
# Generators
# ---------------------------------------------------------------------------

def test_mcq_answer_is_always_among_the_options(db_session):
    course = _seed(db_session, lesson_contents=[_content(6)])
    concepts = collect_concepts(load_course_lessons(course.id, db_session))
    import random

    items = build_mcq(concepts, 6, random.Random(0))
    assert items
    for item in items:
        assert item["options"][item["answer_index"]]
        assert len(set(item["options"])) == len(item["options"]), "no duplicate options"


def test_mcq_pool_spans_lessons(db_session):
    """Distractors come from the whole course, not one lesson."""
    course = _seed(db_session, lesson_contents=[_content(2), _content(2)])
    concepts = collect_concepts(load_course_lessons(course.id, db_session))
    # Two lessons contribute concepts with identical generated names, so
    # de-duplication should collapse them.
    assert len(concepts) == 4


def test_mcq_returns_nothing_below_the_floor(db_session):
    import random

    course = _seed(db_session, lesson_contents=[_content(2)])
    concepts = collect_concepts(load_course_lessons(course.id, db_session))
    assert build_mcq(concepts, 5, random.Random(0)) == []


def test_order_shuffles_and_can_be_solved(db_session):
    import random

    course = _seed(db_session, lesson_contents=[_content(3, steps=5)])
    step_sets = collect_step_sets(load_course_lessons(course.id, db_session))
    items = build_order(step_sets, 5, random.Random(1))
    assert items
    item = items[0]
    ordered = [f"do thing number {i}." for i in range(5)]
    assert item["steps"] != ordered, "must shuffle"
    # correct_order holds display indices in the order they belong.
    restored = [item["steps"][i] for i in item["correct_order"]]
    assert restored == ordered


def test_order_skips_examples_with_too_few_steps(db_session):
    course = _seed(db_session, lesson_contents=[_content(4, steps=2)])
    assert collect_step_sets(load_course_lessons(course.id, db_session)) == []


def test_pronounce_falls_back_to_name_when_example_is_empty(db_session):
    import random

    course = _seed(db_session, lesson_contents=[_content(4)])
    concepts = collect_concepts(load_course_lessons(course.id, db_session))
    items = build_pronounce(concepts, 10, random.Random(0))
    assert items
    assert all(item["phrase"] for item in items), "empty example must fall back to the name"


# ---------------------------------------------------------------------------
# The spoken text must not name the answer
# ---------------------------------------------------------------------------

def _concept_names(course, db_session) -> set[str]:
    return {
        c.name for c in collect_concepts(load_course_lessons(course.id, db_session))
    }


def test_listen_speaks_the_clue_and_never_the_definition(db_session):
    """The definition is the one text that must not be spoken: it names its term."""
    import random

    course = _seed(db_session, lesson_contents=[_content(6)])
    lessons = load_course_lessons(course.id, db_session)
    concepts = collect_concepts(lessons)

    items = build_listen(concepts, 6, random.Random(0))
    assert items

    clues = {c.clue for c in concepts}
    definitions = {c.definition for c in concepts}
    for item in items:
        assert item["speak"] in clues
        assert item["speak"] not in definitions


def test_no_spoken_clue_contains_any_concept_name(db_session):
    """The property the whole feature exists to guarantee, asserted against real
    generated items rather than against the validator's own unit tests."""
    import random

    course = _seed(db_session, lesson_contents=[_content(6), _content(6)])
    lessons = load_course_lessons(course.id, db_session)
    names = _concept_names(course, db_session)

    for item in build_listen(collect_concepts(lessons), 12, random.Random(3)):
        spoken = item["speak"].casefold()
        for name in names:
            assert name.casefold() not in spoken, f"{name!r} is spoken in its own clue"


def test_mcq_prompts_with_the_clue_not_the_definition(db_session):
    import random

    course = _seed(db_session, lesson_contents=[_content(6)])
    concepts = collect_concepts(load_course_lessons(course.id, db_session))

    items = build_mcq(concepts, 6, random.Random(0))
    assert items
    clues = {c.clue for c in concepts}
    for item in items:
        assert item["prompt"] in clues


def test_neither_choice_drill_leaks_the_answer_through_its_id(db_session):
    """The id used to read `mcq-<lesson>-<answer>`, which named the correct option
    in the payload even for a learner who never played the audio."""
    import random

    course = _seed(db_session, lesson_contents=[_content(6)])
    concepts = collect_concepts(load_course_lessons(course.id, db_session))

    for builder in (build_mcq, build_listen):
        for item in builder(concepts, 6, random.Random(1)):
            for option in item["options"]:
                assert option.casefold() not in item["id"].casefold()


def test_listen_asks_nothing_when_no_concept_has_a_clue(db_session):
    """No fallback to the definition. A drill that hands over its answer is worse
    than no drill, so an unclued concept is not asked about at all."""
    import random

    course = _seed(db_session, lesson_contents=[_content(6)], clues=[None])
    concepts = collect_concepts(load_course_lessons(course.id, db_session))

    assert build_listen(concepts, 6, random.Random(0)) == []
    assert build_mcq(concepts, 6, random.Random(0)) == []


def test_a_partly_clued_course_only_asks_the_clued_concepts(db_session):
    """Partial coverage is the normal case mid-backfill, so it must degrade to a
    smaller drill rather than to no drill or to a leaking one."""
    import random

    partial = json.dumps({
        "clues": {
            "Concept 0": "A description of the situation in case zero and what follows from it.",
            "Concept 1": "A description of the situation in case one and what follows from it.",
            "Concept 2": "A description of the situation in case two and what follows from it.",
        }
    })
    course = _seed(db_session, lesson_contents=[_content(6)], clues=[partial])
    concepts = collect_concepts(load_course_lessons(course.id, db_session))

    items = build_listen(concepts, 6, random.Random(0))
    assert len(items) == 3

    clued = {c.name for c in concepts if c.clue}
    for item in items:
        assert item["options"][item["answer_index"]] in clued


def test_a_course_with_content_but_no_clues_explains_the_gap(client, db_session):
    """Two different prerequisites, two different waits: "open a lesson" and
    "the clues are still generating" are not the same instruction to a learner."""
    course = _seed(db_session, lesson_contents=[_content(6)], clues=[None])
    drills = {d["kind"]: d for d in client.get(f"/courses/{course.id}/drills").json()["drills"]}

    assert drills["mcq"]["available"] is False
    assert drills["listen"]["available"] is False
    assert "clues" in drills["listen"]["reason"]
    # The drills that do not ask a question are unaffected by a missing clue.
    assert drills["match"]["available"] is True
    assert drills["order"]["available"] is True


def test_a_partly_clued_lesson_is_not_told_to_open_itself_again(client, db_session):
    """The clue pass ran and rejected some descriptions, so `clues_json` is set
    and `ensure_clues` will never retry it. Telling the learner to open the
    lesson would be advice that provably cannot change anything — the second
    dead end this feature has had to avoid."""
    thin = json.dumps({
        "clues": {"Concept 0": "A description of the situation in case zero and what follows from it."}
    })
    course = _seed(db_session, lesson_contents=[_content(6)], clues=[thin])
    drills = {d["kind"]: d for d in client.get(f"/courses/{course.id}/drills").json()["drills"]}

    assert drills["listen"]["available"] is False
    assert drills["listen"]["item_count"] == 1
    assert "open a lesson" not in drills["listen"]["reason"]
    assert "backfill" in drills["listen"]["reason"]


def test_the_listen_endpoint_reveals_nothing_but_the_options(client, db_session):
    """End-to-end: strip the options from the payload and no concept name should
    remain anywhere in it — not in the id, not in the lesson title, nowhere."""
    course = _seed(db_session, lesson_contents=[_content(6)])
    names = _concept_names(course, db_session)

    with patch(TTS_PATCH, return_value=b"RIFFfake"):
        body = client.get(f"/courses/{course.id}/drills/listen?n=6").json()

    assert body["items"]
    for item in body["items"]:
        rest = json.dumps({k: v for k, v in item.items() if k != "options"})
        for name in names:
            assert name.casefold() not in rest.casefold()


def test_empty_pitfalls_and_prompts_break_nothing(db_session):
    """The enrichment validator accepts their absence, so drills must too."""
    course = _seed(db_session, lesson_contents=[_content(4)])
    lessons = load_course_lessons(course.id, db_session)
    availability = drill_availability(course, lessons)
    assert availability["drills"]


# ---------------------------------------------------------------------------
# Item endpoints
# ---------------------------------------------------------------------------

def test_get_mcq_items(client, db_session):
    course = _seed(db_session, lesson_contents=[_content(5)])
    body = client.get(f"/courses/{course.id}/drills/mcq?n=3").json()
    assert body["kind"] == "mcq"
    assert len(body["items"]) == 3
    assert "prompt" in body["items"][0]


def test_get_drill_409s_when_content_is_insufficient(client, db_session):
    course = _seed(db_session, lesson_contents=[None])
    resp = client.get(f"/courses/{course.id}/drills/mcq")
    assert resp.status_code == 409
    assert "Open a lesson" in resp.json()["detail"]


def test_unknown_drill_kind_404s(client, db_session):
    course = _seed(db_session, lesson_contents=[_content(4)])
    assert client.get(f"/courses/{course.id}/drills/nonsense").status_code == 404


def test_listen_never_leaks_the_spoken_text(client, db_session):
    course = _seed(db_session, lesson_contents=[_content(5)])
    with patch(TTS_PATCH, return_value=b"RIFFfake"):
        body = client.get(f"/courses/{course.id}/drills/listen?n=3").json()

    assert body["items"]
    for item in body["items"]:
        assert "speak" not in item, "sending the text would defeat a listening drill"
        assert "prompt" not in item
        assert item["audio_url"].startswith("/audio/")
        assert item["options"][item["answer_index"]]


def test_listen_503s_when_the_voice_is_missing(client, db_session):
    course = _seed(db_session, lesson_contents=[_content(5)])
    with patch(TTS_PATCH, side_effect=RuntimeError("voice not found")):
        resp = client.get(f"/courses/{course.id}/drills/listen")
    assert resp.status_code == 503


def test_complete_records_an_event_without_touching_cards(client, db_session):
    course = _seed(db_session, lesson_contents=[_content(4)])
    resp = client.post(f"/courses/{course.id}/drills/mcq/complete?correct=3&total=4")
    assert resp.status_code == 204


# ---------------------------------------------------------------------------
# Worked-example splitting
# ---------------------------------------------------------------------------

def test_split_steps_handles_newline_separated():
    from app.services.drills import split_steps

    assert len(split_steps("Step 1: a.\nStep 2: b.\nStep 3: c.")) == 3


def test_split_steps_handles_inline_markers():
    """What the model actually returns: one line of "Step 1: ... Step 2: ..."."""
    from app.services.drills import split_steps

    raw = (
        "Step 1: Open a file named 'data.txt' in read mode. "
        "Step 2: Assign the returned file object to a variable. "
        "Step 3: Call read() on it. "
        "Step 4: Close the handle."
    )
    steps = split_steps(raw)
    assert len(steps) == 4
    assert steps[0].startswith("Open a file")
    assert steps[3].startswith("Close the handle")


def test_split_steps_handles_numbered_prose():
    from app.services.drills import split_steps

    assert split_steps("1. First thing. 2. Second thing. 3. Third thing.") == [
        "First thing.",
        "Second thing.",
        "Third thing.",
    ]


# ---------------------------------------------------------------------------
# The ordering drill must not print its own answer
# ---------------------------------------------------------------------------

_MARKER_START = re.compile(r"^\s*(?:step\s*\d|\d+\s*[.)])", re.IGNORECASE)


@pytest.mark.parametrize(
    "raw",
    [
        "Step 1: a first thing.\nStep 2: a second thing.\nStep 3: a third thing.",
        "Step 1: a first thing. Step 2: a second thing. Step 3: a third thing.",
        "1. a first thing. 2. a second thing. 3. a third thing.",
        "Step 1 - a first thing.\nStep 2 - a second thing.\nStep 3 - a third thing.",
    ],
    ids=["newline", "inline", "numbered", "dashed"],
)
def test_no_step_keeps_its_ordinal_marker(raw):
    """With the marker left in, the drill is solvable without reading a word."""
    from app.services.drills import split_steps

    steps = split_steps(raw)
    assert len(steps) == 3
    for step in steps:
        assert not _MARKER_START.match(step), f"{step!r} still leaks its position"


def test_a_decimal_is_not_mistaken_for_a_marker():
    from app.services.drills import split_steps

    assert split_steps("3.14 is pi.\n2.71 is e.\n1.41 is root two.") == [
        "3.14 is pi.",
        "2.71 is e.",
        "1.41 is root two.",
    ]


def test_order_items_carry_no_markers(db_session):
    """End to end: what build_order hands the client must be marker-free."""
    from app.services.drills import build_order, collect_step_sets, load_course_lessons

    course = _seed(db_session, lesson_contents=[_content(3, steps=5)])
    lessons = load_course_lessons(course.id, db_session)
    items = build_order(collect_step_sets(lessons), 4, random.Random(0))

    assert items, "expected at least one ordering item"
    for item in items:
        for step in item["steps"]:
            assert not _MARKER_START.match(step)


def test_split_steps_returns_few_when_there_is_no_structure():
    from app.services.drills import split_steps

    assert len(split_steps("Just one continuous explanation with no steps.")) < 3


def test_order_available_for_inline_step_content(client, db_session):
    """Regression: inline steps made the ordering drill permanently unavailable."""
    inline = json.dumps(
        {
            "key_concepts": [
                {"name": "A", "definition": "A long enough definition of the concept A.", "example": ""},
                {"name": "B", "definition": "A long enough definition of the concept B.", "example": ""},
            ],
            "worked_example": "Step 1: do this. Step 2: then this. Step 3: finally this.",
            "common_pitfalls": [],
            "practice_prompts": [],
        }
    )
    course = _seed(db_session, lesson_contents=[inline])
    drills = {d["kind"]: d for d in client.get(f"/courses/{course.id}/drills").json()["drills"]}
    assert drills["order"]["available"] is True
